# Start from a base Go image
FROM golang:1.24-bullseye AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download the Go module dependencies
RUN go mod download

# Copy the app source code
COPY main.go .

# Set env var to build for arm64
ENV GOOS=linux CGO_ENABLED=0 GOARCH=arm64

# Build the Go app
RUN go build -o app .

# Start from a lightweight Debian image
FROM scratch AS app

# Set the working directory inside the container
WORKDIR /app

# Copy the built Go binary from the builder stage
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /app .
COPY calendar_template.png .
COPY Roboto-Bold.ttf .

ENV GIN_MODE=release

# Run the Go app
CMD ["./app"]
